apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-download-config
data:
 GITHUB_MODEL_URL: "https://github.com/Ruwais-zaid/alzheimer-mri-classifier.git"
 MODEL_PATH: "alheimers/resnetmodel.pt"