name: Alzheimer MRI Classifier CI/CD

on:
  push:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: zaidtalha123
  IMAGE_NAME: alzheimer-mri-classifier
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Uncomment when you have a reachable cluster
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #
      # - name: Configure kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
      #
      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f k8s/ --validate=false
      #     kubectl set image deployment/alzheimer-mri-classifier \
      #       alzheimer-mri-classifier=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     kubectl rollout status deployment/alzheimer-mri-classifier --timeout=60s || true
