name: Alzheimer MRI Classifier Deploy (Debug)

on:
  push:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: zaidtalha123
  IMAGE_NAME: alzheimer-mri-classifier
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # Debug Git info
      - name: Debug Git info
        run: |
          echo ">>> Git status"
          git status || true
          echo ">>> Branches"
          git branch -a || true
          echo ">>> Last commit"
          git log -1 || true
          echo ">>> Remote info"
          git remote -v || true

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      # Configure kubeconfig
      - name: Configure k3d kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      # Docker login + pull image
      - name: Docker login & pull image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} || echo "Image not found, skipping pull"

      # Deploy to Kubernetes (skip validation)
      - name: Deploy to k3d
        run: |
          echo ">>> Applying Kubernetes manifests (skip validation)"
          kubectl apply -f k8s/ --validate=false

          echo ">>> Updating Deployment image"
          kubectl set image deployment/alzheimer-mri-classifier \
            alzheimer-mri-classifier=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --validate=false

          echo ">>> Waiting for rollout"
          kubectl rollout status deployment/alzheimer-mri-classifier --timeout=60s || true
