name: Alzheimer MRI Classifier Deploy (Debug)

on:
  push:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: zaidtalha123
  IMAGE_NAME: alzheimer-mri-classifier
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout with full history + debug
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # full history for debugging
          submodules: false       # skip submodules unless you need them
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Git info
        run: |
          echo ">>> Git status"
          git status || true
          echo ">>> Branches"
          git branch -a || true
          echo ">>> Last commit"
          git log -1 || true
          echo ">>> Remote info"
          git remote -v || true

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure k3d kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Docker login & pull image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} || echo "Image not found, skipping pull"

      - name: Deploy to k3d
        run: |
          echo ">>> Applying Kubernetes manifests"
          kubectl apply -f k8s/ || exit 1

          echo ">>> Updating Deployment image"
          kubectl set image deployment/alzheimer-mri-classifier \
            alzheimer-mri-classifier=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          echo ">>> Waiting for rollout"
          kubectl rollout status deployment/alzheimer-mri-classifier
