name: Alzheimer MRI Classifier CI/CD

on:
  push:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: zaidtalha123
  IMAGE_NAME: myapp
  IMAGE_TAG: latest

jobs:
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Kubernetes deployment (commented out for local testing)
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #
      # - name: Configure kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
      #
      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f k8s/ --validate=false
      #     kubectl set image deployment/myapp \
      #       myapp=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     kubectl rollout status deployment/myapp --timeout=120s
